jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        platform: x64
        version: latest
    - continue-on-error: true
      name: Setup NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26b
    - continue-on-error: true
      name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.16
    - continue-on-error: true
      name: Gradle caches
      uses: actions/cache@v3
      with:
        key: caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Gradle wrapper caches
      uses: actions/cache@v3
      with:
        key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Fetch buck
      run: '(rm -rf buck && mkdir buck && \

        wget https://jitpack.io/com/github/facebook/buck/v2022.05.05.01/buck-v2022.05.05.01-java11.pex
        && \

        mv buck-v2022.05.05.01-java11.pex buck/buck && \

        chmod +x buck/buck && \

        ls -l buck)

        '
    - continue-on-error: true
      name: Build everything
      run: BUCK_PATH=`realpath buck/buck` ./gradlew assemble --stacktrace --no-daemon
  deploy:
    if: ${{ needs.deploy-check.outputs.is-snapshot == 'true' }}
    needs:
    - deploy-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        platform: x64
        version: latest
    - continue-on-error: true
      name: Setup NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26b
    - continue-on-error: true
      name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.16
    - continue-on-error: true
      name: Gradle caches
      uses: actions/cache@v3
      with:
        key: caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Gradle wrapper caches
      uses: actions/cache@v3
      with:
        key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Fetch buck
      run: '(rm -rf buck && mkdir buck && \

        wget https://jitpack.io/com/github/facebook/buck/v2022.05.05.01/buck-v2022.05.05.01-java11.pex
        && \

        mv buck-v2022.05.05.01-java11.pex buck/buck && \

        chmod +x buck/buck && \

        ls -l buck)

        '
    - continue-on-error: true
      name: Publish Snapshot
      run: BUCK_PATH=`realpath buck/buck` ./gradlew uploadArchives --stacktrace
  deploy-check:
    if: ${{ github.event_name != 'pull_request' && github.repository == 'facebook/litho'
      }}
    name: Skip deploy if PR or Fork or not a SNAPSHOT version
    needs:
    - build
    - tests
    outputs:
      is-snapshot: ${{ steps.check_snapshot.outputs.IS_SNAPSHOT != '' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      id: check_snapshot
      name: Check if SNAPSHOT version
      run: 'echo "IS_SNAPSHOT=`grep ''VERSION_NAME=[0-9\.]\+-SNAPSHOT'' gradle.properties)`"
        >> $GITHUB_OUTPUT

        '
  tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        platform: x64
        version: latest
    - continue-on-error: true
      name: Setup NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26b
    - continue-on-error: true
      name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.16
    - continue-on-error: true
      name: Gradle caches
      uses: actions/cache@v3
      with:
        key: caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Gradle wrapper caches
      uses: actions/cache@v3
      with:
        key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Fetch buck
      run: '(rm -rf buck && mkdir buck && \

        wget https://jitpack.io/com/github/facebook/buck/v2022.05.05.01/buck-v2022.05.05.01-java11.pex
        && \

        mv buck-v2022.05.05.01-java11.pex buck/buck && \

        chmod +x buck/buck && \

        ls -l buck)

        '
    - continue-on-error: true
      name: Run tests
      run: BUCK_PATH=`realpath buck/buck` ./gradlew test -x :litho-intellij-plugin:test
        --stacktrace --no-daemon
name: General CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
