jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: Gradle caches
      uses: actions/cache@v3
      with:
        key: caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Gradle wrapper caches
      uses: actions/cache@v3
      with:
        key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Generate Reference Docs
      run: ./gradlew dokkaHtmlMultiModule
    - continue-on-error: true
      name: Install and Build
      run: 'yarn

        yarn build

        '
      working-directory: website/
    - continue-on-error: true
      name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: website/build
name: Docs
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
