jobs:
  tag:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      id: tag_info
      name: Get tag for the current date
      run: echo "TAG_NAME=$(date +'v%Y.%m.%d')" >> $GITHUB_OUTPUT
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Tag the latest commit
      uses: weareyipyip/walking-tag-action@v2
      with:
        tag-message: ''
        tag-name: ${{ steps.tag_info.outputs.TAG_NAME }}
name: TagIt
on:
  repository_dispatch:
    types: trigger-ga___tagit-weekly.yml
